name: BuildAndTest

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  buildAndTest:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./source
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Coverage
      uses: b3b00/coverlet-action@1.1.7
      with:
        testProject: 'Marten.AspNetCore.Identity.Tests/Marten.AspNetCore.Identity.Tests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[Marten.AspNetCore.Identity.Tests]*,[Marten.IdentityExampleApp]*'
        threshold: 80      
      
# dummy change      
